package httpserver

import (
	"encoding/json"
	"github.com/gin-gonic/gin"
	"io"
	"net/http"
)

type ServerMode string

type Response struct {
	Code int    `json:"code"`
	Data any    `json:"data"`
	Msg  string `json:"msg"`
}

const (
	DebugMode   ServerMode = "debug"
	ReleaseMode ServerMode = "release"
	TestMode    ServerMode = "test"
)

type Server struct {
	handler http.Handler
}

func New(mode ...ServerMode) Server {
	if len(mode) > 0 {
		gin.SetMode(string(mode[0]))
	} else {
		gin.SetMode(string(ReleaseMode))
	}
	return Server{
		handler: gin.Default(),
	}
}

// AddHandlePost Add a POST request processing function that only supports JSON format requests,
// requiring the input parameters to be path and a processing method that accepts JSON format serialization.
func (s *Server) AddHandlePost(path string, f func(input []byte) (Response, error)) {
	s.handler.(*gin.Engine).Handle(http.MethodPost, path, func(c *gin.Context) {
		body := c.Request.Body
		bodyByte, _ := io.ReadAll(body)
		defer body.Close()
		data, err := f(bodyByte)
		if err != nil {
			c.JSON(http.StatusOK, err.Error())
			return
		}
		c.JSON(http.StatusOK, data)
	})
}

// AddHandleGet Add a GET request handling function that only supports query requests,
// Require input parameters to be path and receive the byte of the map generated by the query parameter after serialization.
func (s *Server) AddHandleGet(path string, f func(input []byte) (Response, error)) {
	s.handler.(*gin.Engine).Handle(http.MethodGet, path, func(c *gin.Context) {
		queryParams := c.Request.URL.Query()
		paramMap := make(map[string]string)
		for key, values := range queryParams {
			if len(values) > 0 {
				paramMap[key] = values[0]
			}
		}
		byteData, err := json.Marshal(paramMap)
		if err != nil {
			c.JSON(http.StatusInternalServerError, gin.H{"error": "marshal failed"})
			return
		}
		data, err := f(byteData)
		if err != nil {
			c.JSON(http.StatusOK, err.Error())
			return
		}
		c.JSON(http.StatusOK, data)
	})
}

func (s *Server) Start(addr string) error {
	return http.ListenAndServe(addr, s.handler)
}
